name: Build Environment and Deploy Application

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          path: ~/.m2

      - name: Maven Test
        run: mvn clean test

      - name: Build JAR file
        run: mvn package

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install awscli

      - name: Configure AWS credentials from GitHub Secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload JAR file to AWS S3
        run: aws s3 cp target/*.jar s3://gym-api-app-artifact-bucket/gym-api/${{ github.sha }}.jar

      - name: Deploy JAR file to AWS Elastic Beanstalk
        run: aws elasticbeanstalk create-application-version --application-name gym-api-app --version-label ${{ github.sha }} --source-bundle S3Bucket=gym-api-app-artifact-bucket,S3Key=gym-api/${{ github.sha }}.jar

      - name: Deploy JAR file to AWS Elastic Beanstalk
        run: aws elasticbeanstalk update-environment --environment-name gym-api-app-env --version-label ${{ github.sha }} \
          --environment_variables API_VM_OPTS="-Drds.username=test -Drds.password=test -Drds.url=//gymtracker-dev.crvq5paxn8dg.us-east-2.rds.amazonaws.com\:3306/gymtrackerdb"