name: Build Environment and Deploy Application

on:
  push:
    branches:
      - master

jobs:
  download-state-file:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from GitHub Secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download Terraform state file from S3
        uses: actions/download-artifact@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          bucket-name: "gym-api-tfstate-bucket"
          path: tfstate/terraform.tfstate
          object-key: "your-state-file-name.tfstate"
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  terraform-apply:
    runs-on: ubuntu-latest
    needs: download-state-file
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.8

      - name: Configure AWS credentials from GitHub Secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

  upload-tf-state-file:
    needs: terraform-apply
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials from GitHub Secrets
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload Terraform state file to S3
        uses: actions/upload-artifact@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          bucket-name: "gym-api-tfstate-bucket"
          path: tfstate/terraform.tfstate
          object-key: "your-state-file-name.tfstate"
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#  build:
#    needs: upload-tf-state-file
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up Java environment
#        uses: actions/setup-java@v3
#        with:
#          java-version: '17'
#
#      - name: Cache Maven packages
#        uses: actions/cache@v3
#        with:
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          path: ~/.m2
#
#      - name: Build JAR file
#        run: mvn package
#
#      - name: Upload JAR file to AWS S3
#        uses: aws-actions/upload-artifact-to-s3@v2
#        with:
#          aws-region: ${{ secrets.AWS_REGION }}
#          bucket-name: gym-api-app-artifact-bucket
#          path: target/*.jar
#          object-key: gym-api/${{ github.sha }}.jar
#          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Download JAR file from S3
#        uses: actions/download-artifact@v2
#        with:
#          aws-region: ${{ secrets.AWS_REGION }}
#          bucket-name: gym-api-app-artifact-bucket
#          path: target/*.jar
#          object-key: gym-api/${{ github.sha }}.jar
#          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
